on: issues
name: Add a new GitHub issue to Project board
jobs:
  add-issues-to-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: add-issues-to-project
      uses: takanabe/add-new-issues-to-project-column@v0.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_NAME: Stream Closed Captioner
        PROJECT_COLUMN_NAME: Backlog
